In [1]:
import numpy as np

In [2]:
l1=[1,2,3]

In [3]:
a1=np.array(l1)
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.ndim

1

In [6]:
a1.size

3

In [7]:
a1.shape

(3,)

In [8]:
a2=np.array([1,2,3])
a2

array([1, 2, 3])

In [9]:
l1.append(2)
l1

[1, 2, 3, 2]

In [10]:
a1+2

array([3, 4, 5])

In [11]:
l2=[[1,2,3],[4,5,6]]

In [12]:
l2

[[1, 2, 3], [4, 5, 6]]

In [13]:
a3=np.array(l2)
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3.ndim

2

In [15]:
a3.size

6

In [16]:
a3.shape

(2, 3)

In [17]:
type(a3)

numpy.ndarray

# 3rd numpy array

In [18]:
l3=[
    [[1,2,3],[2,3,4]],
    [[1,2,3],[2,3,4]],
    [[1,2,3],[2,3,4]]
]

In [19]:
a3=np.array(l3)
a3

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [20]:
a3.shape

(3, 2, 3)

In [21]:
a3.dtype

dtype('int32')

# zeros function

In [22]:
a4=np.zeros(5)
a4

array([0., 0., 0., 0., 0.])

In [24]:
a5=np.zeros((2,3))

In [25]:
a5

array([[0., 0., 0.],
       [0., 0., 0.]])

# ones

In [27]:
a6=np.ones((5,))
a6

array([1., 1., 1., 1., 1.])

In [28]:
a7=np.ones((2,1),dtype='int')
a7

array([[1],
       [1]])

# eye

In [29]:
a8=np.eye(4)
a8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
a9=np.eye(4,5)
a9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

# random

In [31]:
a10=np.random.rand(10)
a10

array([0.66895255, 0.11145186, 0.71521902, 0.83105819, 0.04811433,
       0.07169225, 0.83543818, 0.73388528, 0.87445167, 0.03198733])

In [32]:
a11=np.random.rand(3,2)

In [33]:
a11

array([[0.52912341, 0.08742237],
       [0.80656985, 0.36235118],
       [0.45837039, 0.52726201]])

In [34]:
a12=np.random.randint(1,5,size=(2,3))
a12

array([[3, 3, 1],
       [1, 1, 1]])

In [35]:
a13=a12.astype('float')

In [36]:
a13

array([[3., 3., 1.],
       [1., 1., 1.]])

In [37]:
a13.dtype

dtype('float64')

In [38]:
a14=np.random.randn(4)
a14

array([ 0.20123485,  0.4388698 , -0.1601981 , -0.59836551])

In [39]:
a15=np.random.randn(2,3)
a15

array([[-0.79522835, -0.73924728,  0.24914255],
       [ 0.94060202,  1.49136695, -0.02955045]])

# diagn

In [40]:
a16=np.diag([1,2,3,4])
a16

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
np.diag(a16)

array([1, 2, 3, 4])

In [42]:
np.diag(a12)

array([3, 1])

In [43]:
a17=np.arange(1,11)
a17

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a17.shape

(10,)

In [45]:
a17.size

10

In [46]:
a18=np.arange(1,11,2)
a18

array([1, 3, 5, 7, 9])

In [47]:
a19=np.arange(1,11,3)

In [48]:
a19

array([ 1,  4,  7, 10])

# reshape


In [49]:
a17.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
a17.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [51]:
a21=np.arange(1,101)
a21

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [52]:
a22=a21.reshape(2,5,10)

In [53]:
a22

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [54]:
a22.shape

(2, 5, 10)

In [55]:
a23=np.random.randint(1,100,50)
a23

array([94, 43, 49, 51, 62, 75, 81, 80, 65, 55,  7,  4, 41, 49, 37, 82, 36,
       59, 68, 86, 84, 63, 43, 26, 33,  8, 58, 32, 29, 12, 96, 95, 21, 54,
        5,  7, 99,  7,  8, 92, 57, 76, 79, 63, 88, 60, 29, 58, 78, 83])

In [56]:
a24=a23.reshape(2,5,5)

In [57]:
a24

array([[[94, 43, 49, 51, 62],
        [75, 81, 80, 65, 55],
        [ 7,  4, 41, 49, 37],
        [82, 36, 59, 68, 86],
        [84, 63, 43, 26, 33]],

       [[ 8, 58, 32, 29, 12],
        [96, 95, 21, 54,  5],
        [ 7, 99,  7,  8, 92],
        [57, 76, 79, 63, 88],
        [60, 29, 58, 78, 83]]])

In [58]:
a23.reshape(-1,5)

array([[94, 43, 49, 51, 62],
       [75, 81, 80, 65, 55],
       [ 7,  4, 41, 49, 37],
       [82, 36, 59, 68, 86],
       [84, 63, 43, 26, 33],
       [ 8, 58, 32, 29, 12],
       [96, 95, 21, 54,  5],
       [ 7, 99,  7,  8, 92],
       [57, 76, 79, 63, 88],
       [60, 29, 58, 78, 83]])

In [59]:
a23.reshape(5,-1)

array([[94, 43, 49, 51, 62, 75, 81, 80, 65, 55],
       [ 7,  4, 41, 49, 37, 82, 36, 59, 68, 86],
       [84, 63, 43, 26, 33,  8, 58, 32, 29, 12],
       [96, 95, 21, 54,  5,  7, 99,  7,  8, 92],
       [57, 76, 79, 63, 88, 60, 29, 58, 78, 83]])

In [60]:
np.random.seed(4)
a25=np.random.rand(4,5)
a25

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599, 0.69772882],
       [0.2160895 , 0.97627445, 0.00623026, 0.25298236, 0.43479153],
       [0.77938292, 0.19768507, 0.86299324, 0.98340068, 0.16384224],
       [0.59733394, 0.0089861 , 0.38657128, 0.04416006, 0.95665297]])

# Indexing

In [61]:
a26=np.array([1,2,3,4,5])

In [62]:
a26[0]

1

In [63]:
a26[0:3]

array([1, 2, 3])

In [64]:
a26[0:3:2]

array([1, 3])

In [66]:
a27=np.array([[1,2,3,4,5],[1,2,3,4,5]])
a27

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [67]:
a27[0][0]

1

In [68]:
a27[0:2,3:]

array([[4, 5],
       [4, 5]])

In [69]:
a27[0:,3:]

array([[4, 5],
       [4, 5]])