In [1]:
   import numpy as np

In [4]:
l1=[1,2,3]
l1

[1, 2, 3]

# Create a 1d numpy array using list

In [5]:
a1=np.array(l1)
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a1.size

3

In [8]:
a1.ndim

1

In [9]:
a1.shape

(3,)

In [10]:
a2=np.array([1,2,3])
a2

array([1, 2, 3])

In [13]:
l2=[[1,2,3],[4,5,6]]

In [14]:
a3=np.array(l2)

In [15]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
l2.append(5)

In [17]:
l2

[[1, 2, 3], [4, 5, 6], 5]

In [19]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a3.dtype

dtype('int32')

In [23]:
a4=np.array(l1,dtype='float')

In [24]:
a4

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
a3.ndim

2

In [28]:
l4=[[[1,2,3],[2,2,2]],[[1,2,3],[2,2,2]],[[1,2,3],[2,2,2]]]

In [29]:
a5=np.array(l4)

In [30]:
a5

array([[[1, 2, 3],
        [2, 2, 2]],

       [[1, 2, 3],
        [2, 2, 2]],

       [[1, 2, 3],
        [2, 2, 2]]])

In [31]:
a5.size

18

In [32]:
a5.ndim

3

In [33]:
a5.shape

(3, 2, 3)

# Functions

In [34]:
a6=np.zeros(5)

In [35]:
a6

array([0., 0., 0., 0., 0.])

In [37]:
a7=np.zeros((2,3))

In [38]:
a7

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
a8=np.ones(5)

In [40]:
a8

array([1., 1., 1., 1., 1.])

In [46]:
a9=np.ones((2,3))a

In [47]:
a9

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
a9.dtype

dtype('float64')

# convert float to int 

In [50]:
a10=a9.astype('int')

In [51]:
a10

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
a11=np.eye(5)
a11

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
a12=np.eye(3,5)

In [54]:
a12

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [55]:
a12.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.])

In [56]:
np.diag(a11)

array([1., 1., 1., 1., 1.])

# Random

In [57]:
a13=np.random.rand(3,2)

In [58]:
a13

array([[0.7075654 , 0.10422403],
       [0.49388409, 0.64126959],
       [0.03012067, 0.07285101]])

In [59]:
a13

array([[0.7075654 , 0.10422403],
       [0.49388409, 0.64126959],
       [0.03012067, 0.07285101]])

In [60]:
a14=np.random.rand(5)

In [61]:
a14

array([0.07416107, 0.59355797, 0.9663603 , 0.27371138, 0.40923675])

# Randint

In [64]:
a15=np.random.randint(1,10,size=(3,3),dtype='int')

In [65]:
a15

array([[1, 6, 1],
       [4, 6, 7],
       [8, 9, 9]])

In [66]:
a16=np.random.randint(1,30,size=(3,3),dtype='int')

In [67]:
a16

array([[23,  9,  9],
       [ 4, 19, 16],
       [ 8, 26, 27]])

In [68]:
a17=a16.astype('float')

In [69]:
a17

array([[23.,  9.,  9.],
       [ 4., 19., 16.],
       [ 8., 26., 27.]])

# randn-Random Number Generation

In [70]:
a18=np.random.randn(2,4)

In [71]:
a18

array([[-0.7319507 ,  0.07792024, -0.47399969, -0.75864397],
       [-0.50228701,  0.84654219,  1.78798001, -0.87834397]])

In [72]:
a19=np.arange(1,11)
a19

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
a19.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [74]:
a20=a19.reshape(2,5)

In [75]:
a20.shape

(2, 5)

In [78]:
a21=np.random.randint(1,100,50)

In [79]:
a21

array([35, 29, 35, 48, 13, 87, 75, 88, 63, 45, 72, 70, 46, 99, 84, 55, 14,
       84, 60, 27,  2, 45, 95, 27, 87, 72, 65, 11, 76, 23, 37, 87, 76, 60,
       71, 75, 81, 92,  4, 79, 65, 56, 71, 75, 12,  6, 36, 85, 88, 18])

In [80]:
a22=a21.reshape(2,5,5)

In [81]:
a22

array([[[35, 29, 35, 48, 13],
        [87, 75, 88, 63, 45],
        [72, 70, 46, 99, 84],
        [55, 14, 84, 60, 27],
        [ 2, 45, 95, 27, 87]],

       [[72, 65, 11, 76, 23],
        [37, 87, 76, 60, 71],
        [75, 81, 92,  4, 79],
        [65, 56, 71, 75, 12],
        [ 6, 36, 85, 88, 18]]])

In [82]:
a23=a22.reshape(-1,2)
a23

array([[35, 29],
       [35, 48],
       [13, 87],
       [75, 88],
       [63, 45],
       [72, 70],
       [46, 99],
       [84, 55],
       [14, 84],
       [60, 27],
       [ 2, 45],
       [95, 27],
       [87, 72],
       [65, 11],
       [76, 23],
       [37, 87],
       [76, 60],
       [71, 75],
       [81, 92],
       [ 4, 79],
       [65, 56],
       [71, 75],
       [12,  6],
       [36, 85],
       [88, 18]])

In [83]:
a24=a22.reshape(2,-1)

In [84]:
a24

array([[35, 29, 35, 48, 13, 87, 75, 88, 63, 45, 72, 70, 46, 99, 84, 55,
        14, 84, 60, 27,  2, 45, 95, 27, 87],
       [72, 65, 11, 76, 23, 37, 87, 76, 60, 71, 75, 81, 92,  4, 79, 65,
        56, 71, 75, 12,  6, 36, 85, 88, 18]])

# Indexing

In [85]:
a25=np.random.randint(1,10,size=(3,3),dtype='int')

In [86]:
a25

array([[1, 4, 5],
       [5, 9, 1],
       [5, 6, 4]])

In [87]:
a25[0][0]

1

In [88]:
a25[2]

array([5, 6, 4])

In [90]:
a25[:2]

array([[1, 4, 5],
       [5, 9, 1]])

In [91]:
a25[0:2:2]

array([[1, 4, 5]])

In [92]:
a25[0:2:3]

array([[1, 4, 5]])

# Reverse array

In [93]:
a26=a25[::-1]
a26

array([[5, 6, 4],
       [5, 9, 1],
       [1, 4, 5]])

In [94]:
a25[1,1]

9

In [95]:
a25[0,0]

1

# slicing

In [96]:
a25[0:2,0:2]

array([[1, 4],
       [5, 9]])

In [97]:
a25[1: ,1:]

array([[9, 1],
       [6, 4]])

In [98]:
np.random.randint(5,size=(2,4))

array([[3, 3, 2, 4],
       [2, 3, 4, 3]])

In [99]:
np.linspace(1,30,3)

array([ 1. , 15.5, 30. ])